---
title: "Final Project"
author: "Lara Teich"
date: "4/21/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(janitor)
library(rvest)
library(tidyr)
library(tidymodels)
library(tidyverse)
library(reprex)
library(readxl)
library(gganimate)
```
Here is all of my data scraping:  

```{r gather from last time}
library(rvest)
mens_olympic_url_print<- paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=560&associationId=0&teamNumber=0&drawNumber=0")
games2<-read_html(mens_olympic_url_print, encoding = "latin-1")
# this time I piped games2 into div and then table to get past the div barrier. 
games_tab2 <- games2 %>% 
  html_nodes("div") %>%
  html_nodes("table")

# Here, games_tab is a list of html nodes that contain "div" and then "table", singling out all of the results of the games.

single_game <- games_tab2[[1]] %>% html_table(header = T, fill = T) %>% clean_names()
names<- colnames(single_game)
# Here, single_game is turning a single game from my list of games into a tibble. I need to make this work for ALL the games in the doc

```
```{r looped call}
# going to maken empty tibble to later fill in a for loop
mens_test <- tibble()
# this defines x as having the correct setup but no data
x<- single_game %>%  slice(0)
# this for loop fills x every time with a new game from the games_tab list of
# html nodes

for(i in 1: length(games_tab2)) {
  # i is length of games_tab so that it iterates through each
 x <- games_tab2[[i]] %>% 
   # html_table is the function that turns the node into a table
    html_table(header = F, fill = T) %>%
   # this is kinda hacky. I turned header to F so that it fills the column names
   # into the first row, then using slice I isolate the second and third rows,
   # which are the actual data. this produces some amoung of waste since I'm not
   # ignoring the first row as much as I am simply slicing it out after wards,
   # but this is the best I could come up with.
  slice(2:3) 
 mens_test<- rbind(mens_test, x)
 # using rbind I add x to my ever-growing mens_test tibble. 
}
# setting up a vector of actual column names
names<- colnames(single_game)
names <- c(names, "id")
# adding id at the end

mens_test <- mens_test %>% 
  # this mutate call makes some assumptions: it assumes that the for loop worked
  # perfectly and put all the rows into mens_test in perfect order, then this
  # overlays an identifier on top, which goes "1 , 1 , 2, 2..." etc all the way
  # down.
  mutate(id = rep(1:length(games_tab2), each = 2)) %>% 
  `colnames<-`(names)


```

```{r function make}
 # the goal here is to make what I just called above into a function that I
 # merely have to paste the url into. I think I'll start by making that function

womens_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=561&associationId=0&teamNumber=0&drawNumber=0")

#html processing function needs to have an argument for the printurl, which I
#think I'll define outside of the function using paste0 because I don't want to
#mess with putting a long url into a function call.

load_html_list<- function(url) {
  games2<-read_html(url)
  games_tab2 <- games2 %>% 
  html_nodes("div") %>%
  html_nodes("table")
  games_tab2
}

# this function essentially takes a url and makes it into a list of all html
# table elements--essentially, a really messy version of all the games, with
# each line in games_tab2 representing a game.

womens_olympic_html<-load_html_list(womens_olympic_url)
 
# I assigned the list that my function loads to a new variable, which my next
# function will take as its argument. I separated these steps for debugging
# purposes.

get_clean_results<- function(html_list) {
  
  # get_clean_results is the big processing function that I did above to men's olympic results, but all in one place. 
  
  test<- tibble()
  
  #test is the tibble that the data gets layered into, much like how a lasagna
  #is made: one layer at a time.
  
  y<- single_game %>%  slice(0)
  
  # y is each layer of my lasagna, but right now, it is just being formatted so that all the variables are there, just empty. 
  
  for(i in 1: length(html_list)) {
    
    # this takes the length of the html_list because every tournament has a
    # different number of games, and each game represents one row in html_list.
    
    y <- html_list[[i]] %>% 
      html_table(header = F, fill = T) %>%
      slice(2:3)
    
    # like before, I take only the second and third rows of this three row
    # table, because the first is the header that I'd like to erase. my table
    # already has a header; I assigned it outside of this loop.
    
    test<- rbind(test, y)
    
    # now I reassign test to be the previous version of test, plus the new layer
    # of data --the next game, the next layer of lasagna.
    
    }
  names<- colnames(single_game)
  
  # this take the column names of the single game
  
  names <- c(names, "id")
  
  #attaching an "id" column
  
  test <- test %>% 
  mutate(id = rep(1:length(html_list), each = 2)) %>% 
  `colnames<-`(names)
  
  # making test  have an id column to label each game. 
  
  test
}
```
```{r mens and womens cleanup}
# I added a competition label to women's and men's before binding them together to form one big olympics dataset. 
womens_olympic_results<- get_clean_results(womens_olympic_html) %>% 
  mutate(competition = "olympic_women", 
         team_group = c(rep("pool", 94), rep("finals", 4)))

mens_olympic_results<- mens_test %>% 
  mutate(competition = "olympic_men", 
         team_group = c(rep("pool", 95), rep("finals", 5)))



```

```{r putting olympic men and women together, warning = F}


olympics<- rbind(womens_olympic_results, mens_olympic_results)

olympics<- olympics %>% 
  rename(country= draw_number_1_2, 
         hammer = draw_number_1_3, 
         end_score = total) %>% 
  mutate(x7 = as.numeric(x7), 
         x8 = as.numeric(x8), 
         x9 = as.numeric(x9), 
         x10 = as.numeric(x10),
         end_score = as.numeric(end_score))

# here, I made variables that dealt with what interests me the most: whether
# winning the first end is an indicator of winning the whole game. so I made
# indicator variables for each game, sorted by id and competition (since the ids
# repeat for the men and women) that stated which country won the first end and
# which country won the game, making additional logical vectors for both.

olympics <- olympics %>% 
  group_by(competition, id) %>% 
  mutate(first_end_winner = ifelse(x1[1]>x1[2], country[1], 
                                   ifelse(x1[2]>x1[1], country[2], NA)),
         ind_first_end_winner = ifelse(first_end_winner == country, T, F)) %>% 
  mutate(game_winner = 
           ifelse(end_score[1] > end_score[2], country[1], 
                              ifelse(end_score[2]>end_score[1], country[2], NA)), 
         ind_game_winner = ifelse(game_winner == country, T, F)) %>% 
  mutate(first_end_first_game = ifelse(game_winner == first_end_winner, T, F))

```

```{r loading 2014 olympics}
mens_2014_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=381&associationId=0&teamNumber=0&drawNumber=0")
mens_2014_olympic_html<-load_html_list(mens_2014_olympic_url)
mens_2014_olympic_results<- get_clean_results(mens_2014_olympic_html) %>% 
  mutate(competition = "olympic_men", 
         team_group = c(rep("pool", 95), rep("finals", 5)),
         x7 = as.character(x7), 
         x8 = as.character(x8), 
         year = 2014)

womens_2014_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=382&associationId=0&teamNumber=0&drawNumber=0")
womens_2014_olympic_html<-load_html_list(womens_2014_olympic_url)
womens_2014_olympic_results<- get_clean_results(womens_2014_olympic_html) %>% 
  mutate(competition = "olympic_women", 
         team_group = c(rep("pool", 94), rep("finals", 4)), 
         year = 2014)

```

```{r 2010 and 2006 olympics}
# this is really as far back as I'm willing to go, just because the sport has
# changed so much in 10 years and it's become so much more complex. like just
# looking at the photos of the 2002 games I was overwhelmed with how old
# fashioned the brooms looked.really so much has changed and I don't want to
# make my analysis irrelevant.

mens_2010_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=273&associationId=0&teamNumber=0&drawNumber=0")
mens_2010_olympic_html<-load_html_list(mens_2010_olympic_url)
mens_2010_olympic_results<- get_clean_results(mens_2010_olympic_html) %>% 
  mutate(competition = "olympic_men", 
         team_group = c(rep("pool", 95), rep("finals", 5)),
         year = 2010)

womens_2010_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=274&associationId=0&teamNumber=0&drawNumber=0")
womens_2010_olympic_html<-load_html_list(womens_2010_olympic_url)
womens_2010_olympic_results<- get_clean_results(womens_2010_olympic_html) %>% 
  mutate(competition = "olympic_women", 
         team_group = c(rep("pool", 94), rep("finals", 4)), 
         year = 2010)

mens_2006_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=237&associationId=0&teamNumber=0&drawNumber=0")
mens_2006_olympic_html<-load_html_list(mens_2006_olympic_url)
mens_2006_olympic_results<- get_clean_results(mens_2006_olympic_html) %>% 
  mutate(competition = "olympic_men", 
         team_group = c(rep("pool", 94), rep("finals", 4)), 
         year = 2006)

womens_2006_olympic_url<-paste0("https://results.worldcurling.org/Championship/DisplayResults?tournamentId=238&associationId=0&teamNumber=0&drawNumber=0")
womens_2006_olympic_html<-load_html_list(womens_2006_olympic_url)
womens_2006_olympic_results<- get_clean_results(womens_2006_olympic_html) %>% 
  mutate(competition = "olympic_women", 
         team_group = c(rep("pool", 94), rep("finals", 4)), 
         year = 2006)

womens_2018_olympic_results<- womens_olympic_results %>% 
  mutate(year = 2018, 
         team_group = c(rep("pool", 94), rep("finals", 4)))
mens_2018_olympic_results<- mens_olympic_results %>% 
  mutate(year = 2018, 
         team_group = c(rep("pool", 95), rep("finals", 5)))

```
```{r big boi dataframe, warning  = F}
all_years_olympics<-
  bind_rows(
    womens_2006_olympic_results, 
    mens_2006_olympic_results, 
    womens_2010_olympic_results, 
    mens_2010_olympic_results, 
    womens_2014_olympic_results,
    mens_2014_olympic_results,
    womens_2018_olympic_results,
    mens_2018_olympic_results
  )

#repeating the analysis I had done for 2018 olympics only! 

all_years_olympics<- all_years_olympics %>% 
    rename(country= draw_number_1_2, 
         hammer = draw_number_1_3, 
         end_score = total) %>% 
  mutate(x7 = as.numeric(x7), 
         x8 = as.numeric(x8), 
         x9 = as.numeric(x9), 
         x10 = as.numeric(x10),
         end_score = as.numeric(end_score), 
         year = as.character(year)) %>% 
    group_by(year, competition, id) %>% 
  mutate(first_end_winner = ifelse(x1[1]>x1[2], country[1], 
                                   ifelse(x1[2]>x1[1], country[2], "tie")),
         ind_first_end_winner = ifelse(first_end_winner == country, T, F)) %>% 
  mutate(game_winner = 
           ifelse(end_score[1] > end_score[2], country[1], 
                              ifelse(end_score[2]>end_score[1], country[2], "tie")), 
         ind_game_winner = ifelse(game_winner == country, T, F)) %>% 
  mutate(first_end_first_game = ifelse(game_winner == first_end_winner, T, F))
```
```{r making a plot on first end in olympics}
proportion_olympics_quick <- all_years_olympics %>% 
  group_by(year,team_group) %>% 
  summarize(prop_double_win = mean(first_end_first_game, na.rm = T))

ggplot(proportion_olympics_quick, aes(year, prop_double_win, fill = team_group, label = round(prop_double_win, digits = 3))) + 
  geom_bar(stat = "identity", position = "dodge")+ 
  theme_classic()+ 
    labs(
    title = "Proportion of Curling Games 'decided' in the First End", 
    subtitle = "teams who made it to the final round are less affected 2018\nbut more affected in all other years", 
    x = "type of game", 
    y = "Proportion of total games won \nthat were won in the first end", 
    fill = "Team in finals?"
  )+ geom_text(position = position_dodge(width=1))

```

```{r new analysis}
all_years_olympics %>% 
  filter(ind_game_winner == T) %>%  
  group_by(year, competition) %>% 
  summarize(avg_prop_points = mean(x1/end_score)) %>% 
  ggplot(aes(year, avg_prop_points, fill = competition)) + geom_col(position = "dodge")
```

```{r proportion of wins} 
tidy_props<- all_years_olympics %>% 
  select(id,competition, team_group, year, country, ind_game_winner, starts_with("x"), end_score, -x, -x_2) %>% 
  mutate(
    x1_prop = x1/end_score, 
    x2_prop = x2/end_score, 
    x3_prop = x3/end_score, 
    x4_prop = x4/end_score, 
    x5_prop = x5/end_score, 
    x6_prop = x6/end_score, 
    x7_prop = x7/end_score, 
    x8_prop = x8/end_score, 
    x9_prop = x9/end_score, 
    x10_prop = x10/end_score
  ) %>% 
  pivot_longer(
    cols = ends_with("_prop"),
    names_to = "prop"
  ) 
tidy_props$value <- replace_na(tidy_props$value, 0)

tidy_props <- tidy_props %>% 
  filter(ind_game_winner == T)

#ggplot(tidy_props, aes(prop, value)) + geom_col(position = "dodge") +
  #facet_wrap(vars(competition))
ends<-c(1:10)
ggplot(tidy_props, aes(prop, value)) + 
  geom_col(aes(fill = competition)) +
  facet_wrap(vars(year))+
    transition_states(competition,
                    transition_length = 2,
                    state_length = 1) + enter_fade() + exit_fade() +
  theme_classic()+
  labs(
    title = "Proportion of points scored by winners in Olympic Curling Games", 
    subtitle = "the first end for men  in 2018 showed remarkable importance", 
    y = "Proportion of points", 
    x = "end", 
    fill = "Competition"
  ) + 
  scale_x_discrete(labels = ends) + 
  scale_fill_discrete(labels = c("Men", "Women"))

```

```{r multivariate regression}
clean_all_years_olympics <- all_years_olympics %>% 
  mutate(win = ifelse(ind_game_winner == T, 1, 0)) %>% 
  select(id, year, competition, team_group, country, win, starts_with("x"), -x, -x_2, -x10, -x9)

logistic_mod <- logistic_reg() %>%
  set_engine("glm") 

logistic_fit <- fit(logistic_mod,

                    factor(win) ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8,

                    data = clean_all_years_olympics)

logistic_fit

tibble_logistic_fit <- logistic_fit %>%
  tidy(conf.int = TRUE) %>%
  slice(2:8)
  tibble()

ggplot(tibble_logistic_fit, aes(term, estimate)) + 
  geom_bar(stat = "identity") + 
  geom_errorbar(aes(x = term, ymin = conf.low, ymax = conf.high)) + 
  labs(
    title = "Logistic regression coefficients for points per end on winning",
    subtitle = "with 95% confidence interval", 
    x = "end number", 
    y = "Logistic Regression Coefficient"
  )  + 
  scale_x_discrete(labels = ends)

```

```{r collect college}
college_yale_spiel <- read_excel("~/gov1005/college_yale_spiel.xlsx", 
 na = "NA")
college_yale_spiel <- 
  college_yale_spiel %>% 
      group_by(year, id) %>% 
  mutate(first_end_winner = ifelse(x1[1]>x1[2], school[1], 
                                   ifelse(x1[2]>x1[1], school[2], "tie")),
         ind_first_end_winner = ifelse(first_end_winner == school, T, F)) %>% 
  mutate(game_winner = 
           ifelse(end_score[1] > end_score[2], school[1], 
                              ifelse(end_score[2]>end_score[1], school[2], "tie")), 
         ind_game_winner = ifelse(game_winner == school, T, F)) %>% 
  mutate(first_end_first_game = ifelse(game_winner == first_end_winner, T, F))
```
```{r college analysis}
college_chance<-college_yale_spiel %>% 
  group_by(x1) %>% 
  summarize(chance = mean(ind_game_winner)) %>% pull(chance)
olympic_women_chance<-all_years_olympics %>% 
  filter(competition == "olympic_women") %>% 
  group_by(x1) %>% 
  summarize(chance = mean(ind_game_winner)) %>% pull(chance)
olympic_men_chance<-all_years_olympics %>% 
  filter(competition == "olympic_men") %>% 
  group_by(x1) %>% 
  summarize(chance = mean(ind_game_winner)) %>% pull(chance)
chance_everyone <- tibble(
  score = 0:5, 
  pr_men = c(olympic_men_chance, 1), 
  pr_women = olympic_women_chance, 
  pr_college = college_chance
) %>% 
  pivot_longer(
    cols = starts_with("pr_"), 
    names_to = "category", 
    names_prefix = "pr_")
``` 
```{r bootstrapped means}

```

